version: '3.8'

services:
  swarm:
    build: .
    ports:
      - "${PORT:-5000}:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - PROJECT_TRACKER_API_KEY=${PROJECT_TRACKER_API_KEY}
      - PROJECT_TRACKER_URL=${PROJECT_TRACKER_URL}
    volumes:
      - /home/${USER}/Desktop:/app/desktop:ro  # Mount desktop for MCP access
      - .:/app
    restart: unless-stopped
    
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=swarm
      - POSTGRES_USER=${PGUSER:-swarm}
      - POSTGRES_PASSWORD=${PGPASSWORD:-swarm123}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: